[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/esignature-proxy"
  to = "/.netlify/functions/esignature-proxy"
  status = 200